; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps =
	https://github.com/adafruit/Adafruit_Sensor
	madhephaestus/ESP32Servo@^1.2.1
	adafruit/Adafruit ADXL345@1.3.2
	fastled/FastLED


[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_flags =
  -Isrc
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3
lib_deps =
	${common.lib_deps}