#define PIN_GUN_LEFT 1  // PWM
#define PIN_GUN_RIGHT 2  // PWM
#define PIN_WING_LEFT 4  // PWM
#define PIN_WING_RIGHT 5  // PWM
#define PIN_ROTATE_X 6  // PWM
#define PIN_ROTATE_Y 7  // PWM
#define PIN_HALL_LEFT 8  // ADC
#define PIN_HALL_RIGHT 9  // ADC
#define PIN_NEOPIXEL_CENTER 14  // PWM
#define PIN_NEOPIXEL_LEFT 15  // PWM
#define PIN_NEOPIXEL_RIGHT 16  // PWM
#define PIN_RADAR_RX 17  // UART_RX
#define PIN_RADAR_TX 18  // UART_TX
#define PIN_SDA 35  // I2C_SDA
#define PIN_SCL 36  // I2C_SCL
#define PIN_DIN 10  // Custom
#define PIN_BCLK 11  // Custom
#define PIN_LRCLK 12  // Custom